FROM centos:7
# Dockerfile.include1
RUN echo inc1-1
RUN echo inc1-2
RUN echo orgDockerfile
# Dockerfile.include2
RUN echo inc2-1
# Dockerfile.include2-1
RUN echo inc2-1-1
RUN echo inc2-1-2
RUN echo inc2-2
# Dockerfile.include3
RUN echo inc3
# Dockerfile.include3-1
RUN echo inc3-1
RUN echo inc4
RUN echo inc7
